# Generated by Django 4.2.27 on 2026-02-13 18:11

import apps.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('day_of_week', models.IntegerField(choices=[(0, 'یکشنبه'), (1, 'دوشنبه'), (2, 'سه\u200cشنبه'), (3, 'چهارشنبه'), (4, 'پنجشنبه'), (5, 'جمعه'), (6, 'شنبه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='مدت هر نوبت (دقیقه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='doctors.doctor', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'بازه زمانی',
                'verbose_name_plural': 'بازه\u200cهای زمانی',
                'db_table': 'appointment_time_slots',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('patient_name', models.CharField(max_length=255, verbose_name='نام بیمار')),
                ('patient_phone', models.CharField(max_length=15, validators=[apps.core.validators.PhoneNumberValidator()], verbose_name='شماره تماس')),
                ('appointment_date', models.DateField(db_index=True, verbose_name='تاریخ نوبت')),
                ('appointment_time', models.TimeField(db_index=True, verbose_name='زمان نوبت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تأیید شده'), ('cancelled', 'لغو شده'), ('completed', 'تکمیل شده'), ('no_show', 'عدم حضور')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('fee', models.DecimalField(decimal_places=0, help_text='به تومان', max_digits=10, verbose_name='هزینه ویزیت')),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('refunded', 'بازگشت داده شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('symptoms', models.TextField(blank=True, null=True, verbose_name='علائم')),
                ('appointment_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='شماره نوبت')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='یادآوری ارسال شده')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'db_table': 'appointments',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
    ]
