# Generated by Django 4.2.28 on 2026-04-30 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_electronicprescription_invoice_patientprofile_and_more'),
        ('appointments', '0003_appointment_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='patients.patientprofile', verbose_name='بیمار'),
        ),
    ]
