# Generated by Django 4.2.27 on 2026-01-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='ABOUT OUR HOSPITAL', max_length=100)),
                ('title', models.CharField(default='Experience <b>Excellence</b> in Modern Healthcare', max_length=255)),
                ('paragraph_1', models.TextField()),
                ('paragraph_2', models.TextField(blank=True)),
                ('feature_1', models.CharField(default='Expert Doctors', max_length=100)),
                ('feature_2', models.CharField(default='24/7 Support', max_length=100)),
                ('feature_3', models.CharField(default='Modern Equipment', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='<b>Professional</b> Medical Services You Can Trust', max_length=255)),
                ('subtitle', models.TextField(default='Experience world-class healthcare with DoctorHub. From expert diagnosis to advanced treatments, we are here for you.')),
                ('search_placeholder', models.CharField(default='Search Doctors, Clinics, Specialties...', max_length=255)),
                ('active_doctors_count', models.CharField(default='2k+', max_length=50)),
                ('user_rating', models.CharField(default='4.9/5', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Header',
                'verbose_name_plural': 'Landing Page Headers',
            },
        ),
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text='lucide icon name e.g. Heart', max_length=50)),
                ('color_class', models.CharField(default='bg-blue-50 text-blue-600', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PatientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_role', models.CharField(default='Patient', max_length=100)),
                ('review_text', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
