# Generated by Django 4.2.27 on 2026-01-08 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_en', models.CharField(max_length=100)),
                ('label_fa', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, help_text='Internal path like /services or external URL', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon_name', models.CharField(blank=True, help_text='Lucide icon name', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_mega_menu', models.BooleanField(default=False, help_text='If true, show categories/services in a wide dropdown')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.navmenuitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
