# Generated by Django 4.2.27 on 2026-01-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_navmenuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalservice',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='medicalservice',
            old_name='name',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='content_en',
            field=models.TextField(blank=True, help_text='Rich content for the service detail page'),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='content_fa',
            field=models.TextField(blank=True, help_text='Rich content in Persian'),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='description_fa',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='slug',
            field=models.SlugField(default=' ', help_text='Unique URL identifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='title_fa',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
