# Generated by Django 4.2.27 on 2026-01-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_rename_description_medicalservice_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalservice',
            name='slug',
            field=models.SlugField(help_text='Unique URL identifier', unique=True),
        ),
    ]
