# Generated by Django 4.2.28 on 2026-02-21 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_medicalservice_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutsection',
            old_name='feature_1',
            new_name='feature_1_en',
        ),
        migrations.RenameField(
            model_name='aboutsection',
            old_name='feature_2',
            new_name='feature_2_en',
        ),
        migrations.RenameField(
            model_name='aboutsection',
            old_name='feature_3',
            new_name='feature_3_en',
        ),
        migrations.RenameField(
            model_name='aboutsection',
            old_name='paragraph_1',
            new_name='paragraph_1_en',
        ),
        migrations.RenameField(
            model_name='aboutsection',
            old_name='paragraph_2',
            new_name='paragraph_1_fa',
        ),
        migrations.RenameField(
            model_name='aboutsection',
            old_name='tag',
            new_name='tag_en',
        ),
        migrations.RenameField(
            model_name='aboutsection',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='landingpageheader',
            old_name='search_placeholder',
            new_name='search_placeholder_en',
        ),
        migrations.RenameField(
            model_name='landingpageheader',
            old_name='subtitle',
            new_name='subtitle_en',
        ),
        migrations.RenameField(
            model_name='landingpageheader',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='patientreview',
            old_name='patient_name',
            new_name='patient_name_en',
        ),
        migrations.RenameField(
            model_name='patientreview',
            old_name='patient_role',
            new_name='patient_role_en',
        ),
        migrations.RenameField(
            model_name='patientreview',
            old_name='review_text',
            new_name='review_text_en',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='feature_1_fa',
            field=models.CharField(default='Expert Doctors', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='feature_2_fa',
            field=models.CharField(default='24/7 Support', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='feature_3_fa',
            field=models.CharField(default='Modern Equipment', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='paragraph_2_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='paragraph_2_fa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='tag_fa',
            field=models.CharField(default='ABOUT OUR HOSPITAL', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_fa',
            field=models.CharField(default='Experience <b>Excellence</b> in Modern Healthcare', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpageheader',
            name='search_placeholder_fa',
            field=models.CharField(default='Search Doctors, Clinics, Specialties...', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpageheader',
            name='subtitle_fa',
            field=models.TextField(default='Experience world-class healthcare with DoctorHub. From expert diagnosis to advanced treatments, we are here for you.'),
        ),
        migrations.AddField(
            model_name='landingpageheader',
            name='title_fa',
            field=models.CharField(default='<b>Professional</b> Medical Services You Can Trust', max_length=255),
        ),
        migrations.AddField(
            model_name='patientreview',
            name='patient_name_fa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientreview',
            name='patient_role_fa',
            field=models.CharField(default='Patient', max_length=100),
        ),
        migrations.AddField(
            model_name='patientreview',
            name='review_text_fa',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=255)),
                ('question_fa', models.CharField(max_length=255)),
                ('answer_en', models.TextField()),
                ('answer_fa', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='cms.medicalservice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
