# Generated by Django 4.2.27 on 2026-02-13 18:11

import apps.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[apps.core.validators.NationalCodeValidator()], verbose_name='کد ملی')),
                ('phone', models.CharField(max_length=15, unique=True, validators=[apps.core.validators.PhoneNumberValidator()], verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('date_of_birth', models.DateField(verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن'), ('O', 'سایر')], max_length=1, verbose_name='جنسیت')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='گروه خونی')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='قد (سانتی\u200cمتر)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='وزن (کیلوگرم)')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name='نام تماس اضطراری')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, validators=[apps.core.validators.PhoneNumberValidator()], verbose_name='شماره تماس اضطراری')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=100, verbose_name='نسبت')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='patients/profiles/', verbose_name='تصویر پروفایل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران',
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(max_length=255, verbose_name='نام دارو')),
                ('dosage', models.CharField(max_length=100, verbose_name='دوز')),
                ('frequency', models.CharField(max_length=100, verbose_name='فرکانس مصرف')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient', verbose_name='بیمار')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor', verbose_name='تجویز شده توسط')),
            ],
            options={
                'verbose_name': 'دارو',
                'verbose_name_plural': 'داروها',
                'db_table': 'medications',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('condition', models.CharField(max_length=255, verbose_name='بیماری/وضعیت')),
                ('diagnosis_date', models.DateField(verbose_name='تاریخ تشخیص')),
                ('treatment', models.TextField(blank=True, verbose_name='درمان')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'سابقه پزشکی',
                'verbose_name_plural': 'سوابق پزشکی',
                'db_table': 'medical_history',
                'ordering': ['-diagnosis_date'],
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('allergen', models.CharField(max_length=255, verbose_name='آلرژن')),
                ('reaction', models.TextField(verbose_name='واکنش')),
                ('severity', models.CharField(choices=[('mild', 'خفیف'), ('moderate', 'متوسط'), ('severe', 'شدید')], default='mild', max_length=20, verbose_name='شدت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'آلرژی',
                'verbose_name_plural': 'آلرژی\u200cها',
                'db_table': 'allergies',
            },
        ),
    ]
