# Generated by Django 4.2.28 on 2026-04-30 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_electronicprescription_invoice_patientprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 30, 8, 6, 40, 966146, tzinfo=datetime.timezone.utc)),
        ),
    ]
