# Generated by Django 4.2.28 on 2026-04-30 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_invoice_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 30, 8, 22, 40, 160745, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
    ]
