# Generated by Django 4.2.27 on 2025-12-28 17:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '__first__'),
        ('patients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis_text', models.TextField(verbose_name='تشخیص')),
                ('ai_suggestion_log', models.JSONField(blank=True, null=True, verbose_name='لاگ هوش مصنوعی')),
                ('medications', models.JSONField(verbose_name='داروها')),
                ('digital_signature', models.CharField(max_length=255, verbose_name='امضای دیجیتال')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='prescriptions/secure/', verbose_name='فایل نسخه')),
                ('is_dispensed', models.BooleanField(default=False, verbose_name='تحویل داده شده')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='doctors.doctor', verbose_name='پزشک')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'نسخه الکترونیک',
                'verbose_name_plural': 'نسخه\u200cهای الکترونیک',
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
