# Generated by Django 4.2.28 on 2026-04-30 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_invoice_issue_date'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_simple', to='patients.patientprofile', verbose_name='بیمار'),
        ),
    ]
