# Generated by Django 4.2.27 on 2026-02-02 10:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی دارو',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای دارو',
                'db_table': 'pharmacy_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(max_length=255, verbose_name='نام دارو')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('specifications', models.TextField(blank=True, verbose_name='مشخصات فنی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pharmacy/medicines/', verbose_name='تصویر محصول')),
                ('price', models.DecimalField(decimal_places=0, help_text='به تومان', max_digits=12, verbose_name='قیمت')),
                ('stock', models.IntegerField(default=0, verbose_name='موجودی در انبار')),
                ('pharmacy_name', models.CharField(blank=True, max_length=255, verbose_name='نام داروخانه تامین\u200cکننده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_prescription_required', models.BooleanField(default=False, verbose_name='نیاز به نسخه')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='pharmacy.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دارو',
                'verbose_name_plural': 'داروها',
                'db_table': 'pharmacy_medicines',
                'ordering': ['-created_at'],
            },
        ),
    ]
