# Generated by Django 4.2.27 on 2026-02-03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('patients', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='کلید جلسه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
                'db_table': 'pharmacy_carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شماره سفارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تأیید شده'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('refunded', 'بازگشت داده شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('delivery_address', models.TextField(verbose_name='آدرس تحویل')),
                ('delivery_phone', models.CharField(max_length=20, verbose_name='شماره تماس تحویل')),
                ('delivery_name', models.CharField(max_length=200, verbose_name='نام تحویل‌گیرنده')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='جمع Parts')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='تخفیف')),
                ('total', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مجموع')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='روش پرداخت')),
                ('payment_reference', models.CharField(blank=True, max_length=200, verbose_name='شماره پیگیری پرداخت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت‌ها')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_orders', to='patients.patient', verbose_name='بیمار')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='prescriptions.prescription', verbose_name='نسخه')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'db_table': 'pharmacy_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.cart', verbose_name='سبد خرید')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='pharmacy.medicine', verbose_name='دارو')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='prescriptions.prescription', verbose_name='نسخه مرتبط')),
            ],
            options={
                'verbose_name': 'آیتم سبد خرید',
                'verbose_name_plural': 'آیتم‌های سبد خرید',
                'db_table': 'pharmacy_cart_items',
                'unique_together': {('cart', 'medicine')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('medicine_name', models.CharField(max_length=255, verbose_name='نام دارو')),
                ('medicine_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت واحد')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('prescription_item', models.JSONField(blank=True, null=True, verbose_name='آیتم نسخه')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='pharmacy.medicine', verbose_name='دارو')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم‌های سفارش',
                'db_table': 'pharmacy_order_items',
            },
        ),
    ]

