# Generated by Django 4.2.28 on 2026-04-30 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_invoice_issue_date'),
        ('pharmacy', '0002_cart_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='patients.patientprofile', verbose_name='بیمار'),
        ),
        migrations.AlterField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_orders', to='patients.patientprofile', verbose_name='بیمار'),
        ),
    ]
