# Generated by Django 4.2.27 on 2026-01-08 09:14

import apps.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('name_fa', models.CharField(max_length=200, unique=True, verbose_name='نام تخصص (فارسی)')),
                ('name_en', models.CharField(max_length=200, verbose_name='نام تخصص (انگلیسی)')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات (فارسی)')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات (انگلیسی)')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'تخصص\u200cها',
                'db_table': 'specialties',
                'ordering': ['name_fa'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('first_name_fa', models.CharField(max_length=100, verbose_name='نام (فارسی)')),
                ('first_name_en', models.CharField(max_length=100, verbose_name='نام (انگلیسی)')),
                ('last_name_fa', models.CharField(max_length=100, verbose_name='نام خانوادگی (فارسی)')),
                ('last_name_en', models.CharField(max_length=100, verbose_name='نام خانوادگی (انگلیسی)')),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[apps.core.validators.NationalCodeValidator()], verbose_name='کد ملی')),
                ('phone', models.CharField(max_length=15, unique=True, validators=[apps.core.validators.PhoneNumberValidator()], verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('medical_council_number', models.CharField(max_length=20, unique=True, verbose_name='شماره نظام پزشکی')),
                ('sub_specialty_fa', models.CharField(blank=True, max_length=200, verbose_name='فوق تخصص (فارسی)')),
                ('sub_specialty_en', models.CharField(blank=True, max_length=200, verbose_name='فوق تخصص (انگلیسی)')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='سال\u200cهای تجربه')),
                ('education_fa', models.TextField(blank=True, verbose_name='تحصیلات (فارسی)')),
                ('education_en', models.TextField(blank=True, verbose_name='تحصیلات (انگلیسی)')),
                ('clinic_name_fa', models.CharField(max_length=255, verbose_name='نام کلینیک/بیمارستان (فارسی)')),
                ('clinic_name_en', models.CharField(max_length=255, verbose_name='نام کلینیک/بیمارستان (انگلیسی)')),
                ('clinic_address_fa', models.TextField(verbose_name='آدرس (فارسی)')),
                ('clinic_address_en', models.TextField(verbose_name='آدرس (انگلیسی)')),
                ('city_fa', models.CharField(db_index=True, max_length=100, verbose_name='شهر (فارسی)')),
                ('city_en', models.CharField(db_index=True, max_length=100, verbose_name='شهر (انگلیسی)')),
                ('fee', models.DecimalField(decimal_places=0, help_text='به تومان', max_digits=10, verbose_name='هزینه ویزیت')),
                ('accepts_insurance', models.BooleanField(default=False, verbose_name='پذیرش بیمه')),
                ('bio_fa', models.TextField(blank=True, verbose_name='بیوگرافی (فارسی)')),
                ('bio_en', models.TextField(blank=True, verbose_name='بیوگرافی (انگلیسی)')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctors/profiles/', verbose_name='تصویر پروفایل')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='امتیاز')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نظرات')),
                ('patient_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بیماران')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='doctors.specialty', verbose_name='تخصص')),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشکان',
                'db_table': 'doctors',
                'ordering': ['-rating', '-review_count'],
            },
        ),
        migrations.CreateModel(
            name='DoctorWorkingHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('day_of_week', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='doctors.doctor', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'ساعت کاری پزشک',
                'verbose_name_plural': 'ساعات کاری پزشکان',
                'db_table': 'doctor_working_hours',
                'unique_together': {('doctor', 'day_of_week', 'start_time')},
            },
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialty', 'city_fa'], name='doctors_special_602ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialty', 'city_en'], name='doctors_special_b4eb53_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_active', 'is_verified'], name='doctors_is_acti_d2e13d_idx'),
        ),
    ]
